# Generated by Django 2.2.4 on 2019-08-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='last_activity_at',
        ),
    ]
