# Generated by Django 2.2.4 on 2019-08-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0002_remove_scooter_last_activity_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scooter',
            old_name='updated_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='scooter',
            old_name='created_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='scooteractivity',
            old_name='updated_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='scooteractivity',
            old_name='created_at',
            new_name='updated',
        ),
    ]
